CREATE TABLE ACCOUNTS (
    ID IDENTITY,
    NAME VARCHAR(30) NOT NULL,
    ROLE VARCHAR(10) NOT NULL
);

CREATE TABLE EVENT_ROLES (
    ACCOUNT_ID NUMERIC NOT NULL,
    EVENT_ID NUMERIC NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
)